# Generated by Django 3.2.4 on 2021-07-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drink_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('featured', models.BooleanField(verbose_name='Featured')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drink_shop.product'),
        ),
    ]
