# Generated by Django 3.2.4 on 2021-07-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_shop', '0018_auto_20210726_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='apartment_address',
            field=models.CharField(blank=True, default='apartment_address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, default='city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='postal_code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street_address',
            field=models.CharField(blank=True, default='street_address', max_length=100, null=True),
        ),
    ]
